# fly.toml app configuration file generated for system-comment on 2024-11-08T11:05:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'system-comment'
primary_region = 'waw'
console_command = '/code/manage.py shell'

[build]
  dockerfile = "Dockerfile"

[deploy]
release_command = "poetry run python manage.py migrate --noinput"

[env]
SECRET_KEY="django-insecure-jq@h)&nep2c3s54r%r#ip509x03ti+69_b69_!sx@j&4pa*g@z"

DATABASE_NAME="nqzlsvgv"
DATABASE_USER="nqzlsvgv"
DATABASE_PASSWORD="XyF2ctqrxSgDwd6V4QKHYv29JhR2WwKc"
DATABASE_HOST="abul.db.elephantsql.com"
DATABASE_PORT=5432

[experimental]

  enabled = true


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[[services]]
  internal_port = 8000  # Убедитесь, что порт совпадает с портом вашего приложения
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
