# fly.toml app configuration file generated for system-comment on 2024-11-08T11:05:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'system-comment'
primary_region = 'waw'
console_command = '/code/manage.py shell'

[build]
  dockerfile = "Dockerfile"

[deploy]
release_command = "poetry run python manage.py migrate --noinput"

[env]
  SECRET_KEY= "${SECRET_KEY}"

  DATABASE_NAME = "${DATABASE_NAME}"
  DATABASE_USER = "${DATABASE_USER}"
  DATABASE_PASSWORD = "${DATABASE_PASSWORD}"
  DATABASE_HOST = "${DATABASE_HOST}"
  DATABASE_PORT = "${DATABASE_PORT}"

[experimental]

  enabled = true


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[[services]]
  # Настройка основного веб-сервиса
  internal_port = 8000
  protocol = "tcp"

 [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.tcp_checks]]
    # Проверка доступности приложения
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 5
    port = 8000